### ISSUE TITLE
Enabling Grafana on an IBM ROKS Cluster - `jq` not found

### ISSUE THREAD

**Issue by kmlefebv** [cloud-bulldozer/kraken#92]
I enabled Grafana on the `config.yaml` file and received the following message in the OCP Console saying that `jq` was not found. `envsubst` can also not be found. I have `jq` installed locally on the machine I'm using to run the `oc apply -f kraken.yml` command to initialize the deployment.

```
Using k8s command: oc 
Using namespace: dittybopper 
Using default grafana password: admin 

[32mGetting environment vars...[0m 
./deploy.sh: line 111: jq: command not found 
./deploy.sh: line 112: jq: command not found 
Prometheus URL is: 
Prometheus password collected. 

[32mCreating namespace...
[0m namespace/dittybopper created 
[32mDeploying Grafana...[0m 
./deploy.sh: line 122: envsubst: command not found 
error: no objects passed to apply
```

**Comment by chaitanyaenr** [comment]
@kmlefebv Thanks for reporting the issue, think we need to bake in jq and envsubst packages into the container image: https://github.com/cloud-bulldozer/kraken/tree/master/containers.

**Comment by chaitanyaenr** [comment]
@kmlefebv https://github.com/cloud-bulldozer/kraken/pull/93 should fix the issue. Need your review when you get time please.

**Comment by kmlefebv** [comment]
@chaitanyaenr I cloned your PR, kept the configmaps the same, and ran into the same problem with the same error message.

**Comment by kmlefebv** [comment]
I created a new docker image with the changes you made and I did get a different result. Here is the new output:

```
2021-04-27 20:30:14,552 [INFO] Cloning, installing mutable grafana on the cluster and loading the dashboards

[32m
    ____  _ __  __        __
   / __ \(_) /_/ /___  __/ /_  ____  ____  ____  ___  _____
  / / / / / __/ __/ / / / __ \/ __ \/ __ \/ __ \/ _ \/ ___/
 / /_/ / / /_/ /_/ /_/ / /_/ / /_/ / /_/ / /_/ /  __/ /
/_____/_/\__/\__/\__, /_.___/\____/ .___/ .___/\___/_/
                /____/           /_/   /_/

[0m
Using k8s command: oc
Using namespace: dittybopper
Using default grafana password: admin

[32mGetting environment vars...[0m
./deploy.sh: line 111: jq: command not found
./deploy.sh: line 112: jq: command not found
Prometheus URL is:
Prometheus password collected.

[32mCreating namespace...[0m
Looks like the namespace dittybopper already exists, deleting it
namespace "dittybopper" deleted
namespace/dittybopper created

[32mDeploying Grafana...[0m
service/dittybopper created
route.route.openshift.io/dittybopper created
deployment.apps/dittybopper created
configmap/sc-ocp-prom created
configmap/sc-grafana-config created

[32mWaiting for dittybopper deployment to be available...[0m
deployment.apps/dittybopper condition met

You can access the Grafana instance at http://dittybopper-dittybopper.xxxxxxx
```

The Grafana dashboard was created this time, and I was able to access it. However, I still received the `jq` command not found error message.

**Comment by chaitanyaenr** [comment]
@kmlefebv Interesting, looks like it was not able to grab the prometheus url to add it as a datasource. $ oc get secrets -n openshift-monitoring grafana-datasources -o go-template='{{index .data "prometheus.yaml" | base64decode }}' | jq '.datasources[0].url'
 command is used to get it but there's a problem with jq like you mentioned which might be causing it to fail. Will take a look to see why jq is not getting installed properly and let you know. Thanks.

**Comment by chaitanyaenr** [comment]
@kmlefebv epel-release was missing from the image, it's needed to install jq package. It should be fixed now, PTAL. Thanks.

**Comment by chaitanyaenr** [comment]
@kmlefebv The issue should be fixed now that the dependencies are baked in to the image. Please feel free to let us know if there are any problems with the recent image. Thanks.
